# ============================================================
# Sensitivity Analysis: Imbalance — All Species vs Significant Only
# ============================================================
#
# Recomputes imbalance using only species with a statistically
# significant CWD smooth (p < 0.05), and compares the result
# to the primary analysis (all 183 species).
#
# RATIONALE:
#   48% of species show no significant CWD-occurrence relationship.
#   These species contribute near-zero derivatives to imbalance,
#   which could either (a) dilute genuine signal, or (b) legitimately
#   reflect population stability (flat response = not destabilised
#   by CWD). This analysis tests whether results are robust to
#   restricting the species pool to those with detectable CWD responses.
#
#
# DEPENDS ON:
#   imbalance_objects.rds        — output of imbalance_analysis.R
#   gam_evaluation_metrics.csv   — output of gam_evaluation_metrics.R
# ============================================================
#AI Usage: This file was entirely generated by claude sonnet 4.6. It was verified manually and edits were made to remove unnecessary sections. 

# ── 0. Packages ──────────────────────────────────────────────

library(tidyverse)
library(ggplot2)
library(patchwork)


# ── 1. Load objects ───────────────────────────────────────────

objs <- readRDS("imbalance_objects.rds")

pa_matrix    <- objs$pa_matrix     # 183 × 143 presence-absence
deriv_matrix <- objs$deriv_matrix  # 183 × 143 dP/dCWD
masked_deriv <- objs$masked_deriv  # deriv_matrix × pa_matrix
species_list <- objs$species
cwd_groups   <- objs$cwd_groups
results_full <- objs$imbalance     # primary results (all 183 species)

metrics <- read.csv("/Users/aayushmanchalwar/gam_evaluation_metrics.csv", stringsAsFactors = FALSE)

n_cwd <- nrow(cwd_groups)

cat("Loaded", length(species_list), "species and", n_cwd, "CWD groups.\n")


# ── 2. Define significant species subset ─────────────────────

sig_species <- metrics %>%
  filter(p_smooth_sig %in% c("***", "**", "*")) %>%
  pull(species)

n_sig <- length(sig_species)
n_all <- length(species_list)

cat("\nSpecies in primary analysis  :", n_all, "\n")
cat("Species with p < 0.05        :", n_sig,
    sprintf("(%.1f%%)\n", n_sig / n_all * 100))
cat("Species excluded (p >= 0.05) :", n_all - n_sig, "\n\n")

# Confirm all sig_species are present in the matrix row names
stopifnot(
  "Some significant species not found in matrix rownames" =
    all(sig_species %in% rownames(pa_matrix))
)


# ── 3. Recompute imbalance for significant species only ───────


# Subset matrices to significant species only
pa_sig    <- pa_matrix[sig_species, ]
deriv_sig <- masked_deriv[sig_species, ]   # already masked to present sp.

imbalance_sig   <- numeric(n_cwd)
n_present_sig   <- integer(n_cwd)
mean_deriv_sig  <- numeric(n_cwd)

for (j in seq_len(n_cwd)) {

  present_idx      <- which(pa_sig[, j] == 1)
  n_present_sig[j] <- length(present_idx)

  if (length(present_idx) > 0) {
    mean_d              <- mean(deriv_sig[present_idx, j])
    mean_deriv_sig[j]   <- mean_d
    imbalance_sig[j]    <- abs(mean_d)
  } else {
    mean_deriv_sig[j]   <- NA_real_
    imbalance_sig[j]    <- NA_real_
  }
}




comparison <- cwd_groups %>%
  mutate(
    # Primary analysis (all 183 species)
    imbalance_all      = results_full$imbalance,
    n_present_all      = results_full$n_species_present,
    # Sensitivity analysis (88 significant species only)
    imbalance_sig      = imbalance_sig,
    n_present_sig      = n_present_sig,
    # Difference
    abs_diff           = abs(imbalance_all - imbalance_sig),
    rel_diff_pct       = abs_diff / imbalance_all * 100
  )



cor_val  <- cor(comparison$imbalance_all, comparison$imbalance_sig,
                use = "complete.obs", method = "pearson")

rmsd     <- sqrt(mean((comparison$imbalance_all -
                         comparison$imbalance_sig)^2, na.rm = TRUE))
mean_rel <- mean(comparison$rel_diff_pct, na.rm = TRUE)




comparison_long <- comparison %>%
  dplyr::select(CWD, cwd_id,
         `All species\n(n = 183)`   = imbalance_all,
         `Significant only\n(n = 88)` = imbalance_sig) %>%
  pivot_longer(cols      = c(`All species\n(n = 183)`,
                              `Significant only\n(n = 88)`),
               names_to  = "analysis",
               values_to = "imbalance") %>%
  mutate(analysis = factor(analysis,
                           levels = c("All species\n(n = 183)",
                                      "Significant only\n(n = 88)")))




fig1 <- ggplot(comparison_long, aes(x = CWD, y = imbalance,
                                     colour = analysis)) +
  geom_point(size = 1.8, alpha = 0.6) +
  geom_smooth(method  = "gam",
              formula = y ~ s(x, bs = "tp"),
              linewidth = 1.0, se = TRUE, alpha = 0.15) +
  scale_colour_manual(
    name   = "Species pool",
    values = c("All species\n(n = 183)"    = "steelblue3",
               "Significant only\n(n = 88)" = "tomato3")
  ) +
  labs(
    title    = "Sensitivity analysis: imbalance across the CWD gradient",
    subtitle = "Blue = all 183 species; Red = 88 species with significant CWD smooth (p < 0.05)",
    x        = "Climatic Water Deficit (mm)",
    y        = "Imbalance  (|mean dP/dCWD|)"
  ) +
  theme_bw(base_size = 12) +
  theme(legend.position = "bottom")



fig2 <- ggplot(comparison, aes(x = imbalance_all, y = imbalance_sig)) +
  geom_abline(slope = 1, intercept = 0,
              linetype = "dashed", colour = "grey50", linewidth = 0.7) +
  geom_point(aes(colour = CWD), size = 2.5, alpha = 0.85) +
  scale_colour_viridis_c(name = "CWD (mm)", option = "plasma") +
  annotate("text", x = -Inf, y = Inf, hjust = -0.1, vjust = 1.5,
           label = sprintf("Pearson r = %.3f\nSpearman r = %.3f",
                           cor_val, cor_sp),
           size = 4, colour = "black") +
  labs(
    title    = "Agreement between imbalance estimates",
    
    x        = "Imbalance — all 183 species",
    y        = "Imbalance — significant species only (n = 88)"
  ) +
  theme_bw(base_size = 12)



print(fig1)
print(fig2)



